version: '3'

services:
  broker:
    image: broker
    build:
      dockerfile: "./infra/docker/broker/Dockerfile"
      context: "./"

  collector:
    image: collector
    build:
      dockerfile: "./infra/docker/collector/Dockerfile"
      context: "./"

  randgen:
    image: randgen
    build:
      dockerfile: "./infra/docker/randgen/Dockerfile"
      context: "./"
