version: '3'

services:
  mosquitto:
    image: toke/mosquitto
  # External use or debug
    ports:
      - "1883:1883"
    restart:
      always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  collector:
    image: collector
    build:
      dockerfile: "./infra/docker/collector/Dockerfile"
      context: "./"
    ports:
      - "3000:3000"
    depends_on:
      - "mosquitto"
    restart:
      always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  randgen:
    image: randgen
    build:
      dockerfile: "./infra/docker/randgen/Dockerfile"
      context: "./"
    depends_on:
      - "mosquitto"
    restart:
      always
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
