version: '3'

services:
  mosquitto:
    image: toke/mosquitto

  collector:
    image: collector
    build:
      dockerfile: "./infra/docker/collector/Dockerfile"
      context: "./"
    depends_on:
      - "mosquitto"

  randgen:
    image: randgen
    build:
      dockerfile: "./infra/docker/randgen/Dockerfile"
      context: "./"
    depends_on:
      - "mosquitto"
