version: '3'

services:
  mosquitto:
    image: toke/mosquitto
  # External use or debug
  # ports:
  #   - "1883:1883"

  collector:
    image: collector
    build:
      dockerfile: "./infra/docker/collector/Dockerfile"
      context: "./"
    ports:
      - "3000:3000"
    depends_on:
      - "mosquitto"

  randgen:
    image: randgen
    build:
      dockerfile: "./infra/docker/randgen/Dockerfile"
      context: "./"
    depends_on:
      - "mosquitto"
